name: Mise à jour profil GitHub

on:
  schedule:
    - cron: '0 0 * * *'  # tous les jours à minuit UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Snake animation contributions
        uses: Platane/snk@v0.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit des changements
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update contribution snake animation" || echo "Pas de changement"
          git push
