name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *'  # tous les jours à minuit UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Verify README exists
        id: check_readme
        run: |
          if [ ! -f "README.md" ]; then
            echo "README.md not found in the root directory"
            echo "::set-output name=exists::false"
            exit 1
          else
            echo "README.md found"
            echo "::set-output name=exists::true"
          fi
      
      - name: Update stats
        if: steps.check_readme.outputs.exists == 'true'
        run: |
          # Add your stats update commands here
          echo "Updating README stats..."
          # Example: node update-stats.js
          
          # For testing, just add a timestamp
          echo "\n<!-- Last updated: $(date) -->" >> README.md
      
      - name: Commit and Push changes
        if: steps.check_readme.outputs.exists == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Update README stats [skip ci]" && git push) || \
            echo "No changes to commit"
